plugins { id 'com.android.application' }
android {
    compileSdk 34
    defaultConfig {
        applicationId "com.avb.attendance"
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName "2.0-BULK"
    }
    buildTypes { release { minifyEnabled false } }
    namespace 'com.avb.attendance'
}
dependencies { implementation 'androidx.appcompat:appcompat:1.6.1' }plugins { id 'com.android.application' }
android {
    compileSdk 34
    defaultConfig {
        applicationId "com.avb.attendance"
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName "2.0-BULK"
    }
    buildTypes { release { minifyEnabled false } }
    namespace 'com.avb.attendance'
}
dependencies { implementation 'androidx.appcompat:appcompat:1.6.1' }